[build]
  publish = "public"
  functions = "netlify/functions"
  command = ""

[functions]
  node_bundler = "esbuild"
  external_node_modules = ["pg-native"]

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200
  force = true

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "same-origin"
